<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 10: Multiple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="01-foundation_files/libs/clipboard/clipboard.min.js"></script>
<script src="01-foundation_files/libs/quarto-html/tabby.min.js"></script>
<script src="01-foundation_files/libs/quarto-html/popper.min.js"></script>
<script src="01-foundation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="01-foundation_files/libs/quarto-html/anchor.min.js"></script>
<link href="01-foundation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-foundation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="01-foundation_files/libs/quarto-html/quarto-html-435ba6093e6f0817aa7405139811e7b1.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="01-foundation_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">


<link rel="stylesheet" href="../../assets/styles.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Chapter 10: Multiple Linear Regression</h1>
<p class="subtitle">Sections 10.1-10.3 - Foundation</p>

</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-10-multiple-linear-regression" id="toc-chapter-10-multiple-linear-regression"><span class="header-section-number">1</span> Chapter 10: Multiple Linear Regression</a>
  <ul>
  <li><a href="#sec-10-1" id="toc-sec-10-1"><span class="header-section-number">1.1</span> 10.1 Multiple regression: why and when?</a></li>
  <li><a href="#sec-10-2" id="toc-sec-10-2"><span class="header-section-number">1.2</span> 10.2 Multiple linear regression with two explanatory variables</a></li>
  <li><a href="#sec-10-3" id="toc-sec-10-3"><span class="header-section-number">1.3</span> 10.3 Multiple regression and simple regression: Omitted variable bias</a></li>
  <li><a href="#case-study-a1-understanding-the-gender-difference-in-earnings" id="toc-case-study-a1-understanding-the-gender-difference-in-earnings"><span class="header-section-number">1.4</span> Case Study A1: Understanding the Gender Difference in Earnings</a>
  <ul>
  <li><a href="#interpretation-of-results" id="toc-interpretation-of-results"><span class="header-section-number">1.4.1</span> Interpretation of Results</a></li>
  <li><a href="#why-are-women-younger-on-average" id="toc-why-are-women-younger-on-average"><span class="header-section-number">1.4.2</span> Why Are Women Younger on Average?</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
<!-- 
File: 01-foundation-v2.qmd
Version: 2.4 - Explicit resource paths
Created: 2025-10-18
Updated: 2025-10-20
Iterations: 5
Model: Claude Sonnet 4.5 (2025-10-20)
Notes: Added explicit CSS and resource paths for standalone rendering
       Can render as single file or as part of book
-->
<p><link href="https://fonts.googleapis.com/css2?family=Anton&amp;family=Oswald:wght@300;400;500;600;700&amp;family=Roboto+Condensed:wght@300;400;700&amp;family=Lora:wght@400;600&amp;display=swap" rel="stylesheet"></p>
<h1 class="chapter-title" data-number="1" id="chapter-10-multiple-linear-regression"><span class="header-section-number">1</span> Chapter 10: Multiple Linear Regression</h1>
<p><strong>Why and how to carry out multiple linear regression analysis, and how to interpret its results</strong></p>
<div>
<blockquote>
<p><strong>Motivation</strong></p>
<p>There is a substantial difference in the average earnings of women and men in all countries. You want to understand more about the potential origins of that difference, focusing on employees with a graduate degree in your country. You have data on a large sample of employees with a graduate degree, with their earnings and some of their characteristics, such as age and the kind of graduate degree they have. Women and men differ in those characteristics, which may affect their earnings. How should you use this data to uncover gender difference that are not due to differences in those other characteristics? And can you use regression analysis to uncover patterns of associations between earnings and those other characteristics that may help understand the origins of gender differences in earnings?</p>
<p>You have analyzed your data on hotel prices in a particular city to find hotels that are underpriced relative to how close they are to the city center. But you have also uncovered differences in terms of other features of the hotels that measure quality and are related to price. How would you use this data to find hotels that are underpriced relative to all of their features? And how can you visualize the distribution of hotel prices relative to what price you would expect for their features in a way that helps identify underpriced hotels?</p>
</blockquote>
</div>
<p>After understanding simple linear regression, we can turn to multiple linear regression, which has more than one explanatory variable. Multiple linear regression is the most used method to uncover patterns of associations between variables. There are multiple reasons to include more explanatory variables in a regression. We may be interested in uncovering patterns of association between <span class="math inline"><em>y</em></span> and other explanatory variables, which may help understand differences in terms of the <span class="math inline"><em>x</em></span> variable we are interested in most. Or, we may be interested in the effect of an <span class="math inline"><em>x</em></span> variable, but we want to compare observations that are different in <span class="math inline"><em>x</em></span> but similar in other variables. Finally, we may want to predict <span class="math inline"><em>y</em></span>, and we want to use more <span class="math inline"><em>x</em></span> variables to arrive at better predictions.</p>
<p>We discuss why and when we should estimate multiple regression, how to interpret its coefficients, and how to construct and interpret confidence intervals and test the coefficients. We discuss the relationship between multiple regression and simple regression. We explain that piecewise linear splines and polynomial regressions are technically multiple linear regressions without the same interpretation of the coefficients. We discuss how to include categorical explanatory variables as well as interactions that help uncover different slopes for groups. We include an informal discussions on how to decide what explanatory variables to include and in what functional form. Finally, we discuss why a typical multiple regression with observational data can get us closer to causal interpretation without fully uncovering it.</p>
<p>The first case study in this chapter, <strong>Understanding the gender difference in earnings</strong>, uses the cps-earnings data to illustrate the use of multiple regression to understand potential sources of gender differences in earnings. We also go back to our question on finding underpriced hotels relative to their location and quality in the case study <strong>Finding a good deal among hotels with multiple regression</strong>, using the hotels-vienna data, to illustrate the use of multiple regression in prediction and residual analysis.</p>
<p><strong>Learning outcomes.</strong> After working through this chapter, you should be able to</p>
<ul>
<li>identify questions that are best answered with the help of multiple regression from available data;</li>
<li>estimate multiple linear regression coefficients and present and interpret them;</li>
<li>estimate appropriate standard errors, create confidence intervals and tests of regression coefficients, and interpret those;</li>
<li>select the variables to include in a multiple regression guided by the purpose of the analysis;</li>
<li>understand the relationship between the results of a multiple regression and the causal effects of an intervention using observational data.</li>
</ul>
<div>
<blockquote>
<p><strong>🎯 Interactive Enhancements</strong></p>
<p>This HTML version includes: - 🔗 <strong>Dashboard links</strong> to explore concepts visually - 💻 <strong>Codespace links</strong> to run analyses yourself - 🤖 <strong>AI practice tasks</strong> for personalized learning - 📊 <strong>Interactive figures</strong> and tables</p>
</blockquote>
</div>
<hr>
<h2 data-number="1.1" id="sec-10-1" class="anchored"><span class="header-section-number">1.1</span> 10.1 Multiple regression: why and when?</h2>
<p>There are three broad reasons to carry out multiple regression analysis instead of simple regression. The first is exploratory data analysis: we may want to uncover more patterns of association, typically to generate questions for subsequent analysis. The other two reasons are related to one of the two ultimate aims of data analysis: making a better prediction by explaining more of the variation, and getting closer to establishing cause and effect in observational data by comparing observations that are more comparable.</p>
<p>The first example of the introduction is about understanding the reasons of a difference. It’s a causal question of sorts: we are interested in what causes women to earn less than men. The second example is one of prediction: we want to capture average price related to hotel features that customers value in order to identify hotels that are inexpensive compared to what their price “should be.”</p>
<div class="ai-task">
<p><span class="ai-task-icon">🤖 AI PRACTICE TASK #1</span></p>
<p><strong>Prompt:</strong> “I’m studying the relationship between education and earnings. What are three variables I should ‘control for’ in a multiple regression, and why would omitting them bias my results?”</p>
<button class="ai-task-copy" onclick="navigator.clipboard.writeText('I\'m studying the relationship between education and earnings. What are three variables I should control for in a multiple regression, and why would omitting them bias my results?'); alert('Copied to clipboard! Paste into Claude.ai')">
📋 COPY &amp; OPEN IN CLAUDE
</button>
</div>
<hr>
<h2 data-number="1.2" id="sec-10-2" class="anchored"><span class="header-section-number">1.2</span> 10.2 Multiple linear regression with two explanatory variables</h2>
<p>Multiple regression analysis uncovers average <span class="math inline"><em>y</em></span> as a function of more than one <span class="math inline"><em>x</em></span> variable: <span class="math inline"><em>y</em><sup><em>E</em></sup> = <em>f</em>(<em>x</em><sub>1</sub>, <em>x</em><sub>2</sub>, ...)</span>. It can lead to better predictions of <span class="math inline"><em>ŷ</em></span> by considering more explanatory variables. It may improve the interpretation of slope coefficients by comparing observations that are different in terms of one of the <span class="math inline"><em>x</em></span> variables but similar in terms of all other <span class="math inline"><em>x</em></span> variables.</p>
<p>Multiple linear regression specifies a linear function of the explanatory variables for the average <span class="math inline"><em>y</em></span>. Let’s start with the simplest version with two explanatory variables:</p>
<p><span class="math display"><em>y</em><sup><em>E</em></sup> = <em>β</em><sub>0</sub> + <em>β</em><sub>1</sub><em>x</em><sub>1</sub> + <em>β</em><sub>2</sub><em>x</em><sub>2</sub></span></p>
<p>This is the standard notation for a multiple regression: all coefficients are denoted by the Greek letter <span class="math inline"><em>β</em></span>, but they have subscripts. The intercept has subscript 0, the first explanatory variable has subscript 1, and the second explanatory variable has subscript 2.</p>
<p>Having another right-hand-side variable in the regression means that we take the value of that other variable into account when we compare observations. The slope coefficient on <span class="math inline"><em>x</em><sub>1</sub></span> shows the difference in average <span class="math inline"><em>y</em></span> across observations with different values of <span class="math inline"><em>x</em><sub>1</sub></span> but with the same value of <span class="math inline"><em>x</em><sub>2</sub></span>. Symmetrically, the slope coefficient on <span class="math inline"><em>x</em><sub>2</sub></span> shows difference in average <span class="math inline"><em>y</em></span> across observations with different values of <span class="math inline"><em>x</em><sub>2</sub></span> but with the same value of <span class="math inline"><em>x</em><sub>1</sub></span>. This way, multiple regression with two explanatory variables compares observations that are similar in one explanatory variable to see the differences related to the other explanatory variable.</p>
<p>The interpretation of the slope coefficients takes this into account. <span class="math inline"><em>β</em><sub>1</sub></span> shows how much larger <span class="math inline"><em>y</em></span> is on average for observations in the data with one unit larger value of <span class="math inline"><em>x</em><sub>1</sub></span> but the same value of <span class="math inline"><em>x</em><sub>2</sub></span>. <span class="math inline"><em>β</em><sub>2</sub></span> shows how much larger <span class="math inline"><em>y</em></span> is on average for observations in the data with one unit larger value of <span class="math inline"><em>x</em><sub>2</sub></span> but with the same value of <span class="math inline"><em>x</em><sub>1</sub></span>.</p>
<div class="review-box">
<div class="review-box-title">
Multiple Linear Regression
</div>
<p><strong>Multiple linear regression with two explanatory variables</strong></p>
<p><span class="math display"><em>y</em><sup><em>E</em></sup> = <em>β</em><sub>0</sub> + <em>β</em><sub>1</sub><em>x</em><sub>1</sub> + <em>β</em><sub>2</sub><em>x</em><sub>2</sub></span></p>
<p><strong>Interpretation of the coefficients</strong></p>
<ul>
<li><span class="math inline"><em>β</em><sub>0</sub></span> (intercept): Average <span class="math inline"><em>y</em></span> for observations if both <span class="math inline"><em>x</em><sub>1</sub></span> and <span class="math inline"><em>x</em><sub>2</sub></span> are zero in the data.</li>
<li><span class="math inline"><em>β</em><sub>1</sub></span> (slope of <span class="math inline"><em>x</em><sub>1</sub></span>): On average, <span class="math inline"><em>y</em></span> is <span class="math inline"><em>β</em><sub>1</sub></span> units larger in the data for observations with one unit larger <span class="math inline"><em>x</em><sub>1</sub></span> but with the same <span class="math inline"><em>x</em><sub>2</sub></span>.</li>
<li><span class="math inline"><em>β</em><sub>2</sub></span> (slope of <span class="math inline"><em>x</em><sub>2</sub></span>): On average, <span class="math inline"><em>y</em></span> is <span class="math inline"><em>β</em><sub>2</sub></span> units larger in the data for observations with one unit larger <span class="math inline"><em>x</em><sub>2</sub></span> but with the same <span class="math inline"><em>x</em><sub>1</sub></span>.</li>
</ul>
</div>
<div class="ai-task">
<p><span class="ai-task-icon">🤖 AI PRACTICE TASK #2</span></p>
<p><strong>Prompt:</strong> “I ran a regression: Price = 50 + 10×Bedrooms + 5×SquareFeet. How would I interpret the coefficient on Bedrooms? Write it in plain English as if explaining to a non-statistician.”</p>
<button class="ai-task-copy" onclick="navigator.clipboard.writeText('I ran a regression: Price = 50 + 10×Bedrooms + 5×SquareFeet. How would I interpret the coefficient on Bedrooms? Write it in plain English as if explaining to a non-statistician.'); alert('Copied!')">
📋 COPY &amp; OPEN IN CLAUDE
</button>
</div>
<hr>
<h2 data-number="1.3" id="sec-10-3" class="anchored"><span class="header-section-number">1.3</span> 10.3 Multiple regression and simple regression: Omitted variable bias</h2>
<p>It is instructive to examine the difference in the slope coefficient of an explanatory variable <span class="math inline"><em>x</em><sub>1</sub></span> when it is the only variable on the right-hand-side of a regression compared to when another explanatory variable, <span class="math inline"><em>x</em><sub>2</sub></span>, is included as well. In notation, the question is the difference between <span class="math inline"><em>β</em></span> in the simple linear regression</p>
<p><span class="math display"><em>y</em><sup><em>E</em></sup> = <em>α</em> + <em>β</em><em>x</em><sub>1</sub></span></p>
<p>and <span class="math inline"><em>β</em><sub>1</sub></span> in the multiple linear regression</p>
<p><span class="math display"><em>y</em><sup><em>E</em></sup> = <em>β</em><sub>0</sub> + <em>β</em><sub>1</sub><em>x</em><sub>1</sub> + <em>β</em><sub>2</sub><em>x</em><sub>2</sub></span></p>
<p>For example, we may use time series data on sales and prices of the main product of our company, and regress month-to-month change in log quantity sold (<span class="math inline"><em>y</em></span>) on month-to-month change in log price (<span class="math inline"><em>x</em><sub>1</sub></span>). Then <span class="math inline"><em>β</em></span> shows the average percentage change in sales when our price increases by one percent. For example, <span class="math inline"><em>β̂</em> = −0.5</span> would show that sales tend to decrease by half of a percent when our price increases by one percent.</p>
<p>But we would like to know what happens to sales when we change our price but competitors don’t. The second regression has change in the log of the average price charged by our competitors (<span class="math inline"><em>x</em><sub>2</sub></span>) next to <span class="math inline"><em>x</em><sub>1</sub></span>. Here <span class="math inline"><em>β</em><sub>1</sub></span> would answer our question: average percentage change in our sales in months when we increase our price by one percent, but competitors don’t change their price. Suppose that in that regression, we estimate <span class="math inline"><em>β̂</em><sub>1</sub> = −3</span>. That is, our sales tend to drop by 3 percent when we increase our price by 1 percent and our competitors don’t change their prices. Also suppose that the coefficient on <span class="math inline"><em>x</em><sub>2</sub></span> is positive, <span class="math inline"><em>β̂</em><sub>2</sub> = 3</span>. That means that our sales tend to increase by 3 percent when our competitors increase their prices by 1 percent and our price doesn’t change.</p>
<p>As we’ll see, whether the answer to the two questions is the same will depend on whether <span class="math inline"><em>x</em><sub>1</sub></span> and <span class="math inline"><em>x</em><sub>2</sub></span> are related. To understand that relationship, let us introduce the regression of <span class="math inline"><em>x</em><sub>2</sub></span> on <span class="math inline"><em>x</em><sub>1</sub></span>, called the <span class="math inline"><em>x</em> − <em>x</em></span> regression, where <span class="math inline"><em>δ</em></span> is the slope parameter:</p>
<p><span class="math display"><em>x</em><sub>2</sub><sup><em>E</em></sup> = <em>γ</em> + <em>δ</em><em>x</em><sub>1</sub></span></p>
<p>In our own price–competitor price example, <span class="math inline"><em>δ</em></span> would tell us how much the two prices tend to move together. In particular, it tells us about the average percentage change in competitor price in months when our own price increases by one percent. Let’s suppose that we estimate it to be <span class="math inline"><em>δ̂</em> = 0.8</span>: competitors tend to increase their price by 0.8 of a percent when our company increases its price by one percent. The two prices tend to move together, in the same direction.</p>
<p>To link the two original regressions, plug this <span class="math inline"><em>x</em> − <em>x</em></span> regression back in the multiple regression (this step is fine even though that may not be obvious; see Section 10.14):</p>
<p><span class="math display"><em>y</em><sup><em>E</em></sup> = <em>β</em><sub>0</sub> + <em>β</em><sub>1</sub><em>x</em><sub>1</sub> + <em>β</em><sub>2</sub>(<em>γ</em> + <em>δ</em><em>x</em><sub>1</sub>) = <em>β</em><sub>0</sub> + <em>β</em><sub>2</sub><em>γ</em> + (<em>β</em><sub>1</sub> + <em>β</em><sub>2</sub><em>δ</em>)<em>x</em><sub>1</sub></span></p>
<p>Importantly, we find that with regards to <span class="math inline"><em>x</em><sub>1</sub></span>, the slope coefficients in the simple (<span class="math inline"><em>β</em></span>) and multiple regression (<span class="math inline"><em>β</em><sub>1</sub></span>) are different:</p>
<p><span class="math display"><em>β</em> − <em>β</em><sub>1</sub> = <em>δ</em><em>β</em><sub>2</sub></span></p>
<p>The slope of <span class="math inline"><em>x</em><sub>1</sub></span> in a simple regression is different from its slope in the multiple regression, the difference being the product of its slope in the regression of <span class="math inline"><em>x</em><sub>2</sub></span> on <span class="math inline"><em>x</em><sub>1</sub></span> and the slope of <span class="math inline"><em>x</em><sub>2</sub></span> in the multiple regression. Or, put simply, the slope in simple regression is different from the slope in multiple regression by the slope in the <span class="math inline"><em>x</em> − <em>x</em></span> regression times the slope of the other <span class="math inline"><em>x</em></span> in the multiple regression.</p>
<p>This difference is called the <strong>omitted variable bias</strong>. If we are interested in the coefficient on <span class="math inline"><em>x</em><sub>1</sub></span> with <span class="math inline"><em>x</em><sub>2</sub></span> in the regression, too, it’s the second regression that we need, the first regression is an incorrect regression as it omits <span class="math inline"><em>x</em><sub>2</sub></span>. Thus, the results from that first regression are biased, and the bias is caused by omitting <span class="math inline"><em>x</em><sub>2</sub></span>. We will discuss omitted variables bias in detail when discussing causal effects in Chapter 21, Section 21.3.</p>
<p>In our sales–own price–competitors’ price example, we had that <span class="math inline"><em>β̂</em> = −0.5</span> and <span class="math inline"><em>β̂</em><sub>1</sub> = −3</span>, so that <span class="math inline"><em>β̂</em> − <em>β̂</em><sub>1</sub> = −0.5 − (−3) = +2.5</span>. In this case our simple regression gives a biased, overestimated slope on <span class="math inline"><em>x</em><sub>1</sub></span> compared to the multiple regression. Recall that we had <span class="math inline"><em>δ̂</em> = 0.8</span> and <span class="math inline"><em>β̂</em><sub>2</sub> = 3</span>. Their product is approximately 2.5 (2.4, but that difference is due to rounding). This overestimation is the result of two things: a positive association between the two price changes (<span class="math inline"><em>δ</em></span>) and a positive association between competitor price and our own sales (<span class="math inline"><em>β</em><sub>2</sub></span>).</p>
<p>In general, the slope coefficient on <span class="math inline"><em>x</em><sub>1</sub></span> in the two regressions is different unless <span class="math inline"><em>x</em><sub>1</sub></span> and <span class="math inline"><em>x</em><sub>2</sub></span> are uncorrelated (<span class="math inline"><em>δ</em> = 0</span>) or the coefficient on <span class="math inline"><em>x</em><sub>2</sub></span> is zero in the multiple regression (<span class="math inline"><em>β</em><sub>2</sub> = 0</span>). The slope in the simple regression is larger if <span class="math inline"><em>x</em><sub>2</sub></span> and <span class="math inline"><em>x</em><sub>1</sub></span> are positively correlated and <span class="math inline"><em>β</em><sub>2</sub></span> is positive (or they are negatively correlated and <span class="math inline"><em>β</em><sub>2</sub></span> is negative).</p>
<p>The intuition is the following. In the simple regression <span class="math inline"><em>y</em><sup><em>E</em></sup> = <em>α</em> + <em>β</em><em>x</em><sub>1</sub></span>, we compare observations that are different in <span class="math inline"><em>x</em><sub>1</sub></span> without considering whether they are different in <span class="math inline"><em>x</em><sub>2</sub></span>. If <span class="math inline"><em>x</em><sub>1</sub></span> and <span class="math inline"><em>x</em><sub>2</sub></span> are uncorrelated this does not matter. In this case observations that are different in <span class="math inline"><em>x</em><sub>1</sub></span> are, on average, the same in <span class="math inline"><em>x</em><sub>2</sub></span>, and, symmetrically, observations that are different in <span class="math inline"><em>x</em><sub>2</sub></span> are, on average, the same in <span class="math inline"><em>x</em><sub>1</sub></span>. Thus the extra step we take with the multiple regression to compare observations that are different in <span class="math inline"><em>x</em><sub>1</sub></span> but similar in <span class="math inline"><em>x</em><sub>2</sub></span> does not matter here.</p>
<p>If, however, <span class="math inline"><em>x</em><sub>1</sub></span> and <span class="math inline"><em>x</em><sub>2</sub></span> are correlated, comparing observations with or without the same <span class="math inline"><em>x</em><sub>2</sub></span> value makes a difference. If they are positively correlated, observations with higher <span class="math inline"><em>x</em><sub>2</sub></span> tend to have higher <span class="math inline"><em>x</em><sub>1</sub></span>. In the simple regression we ignore differences in <span class="math inline"><em>x</em><sub>2</sub></span> and compare observations with different values of <span class="math inline"><em>x</em><sub>1</sub></span>. But higher <span class="math inline"><em>x</em><sub>1</sub></span> values mean higher <span class="math inline"><em>x</em><sub>2</sub></span> values, too. Corresponding differences in <span class="math inline"><em>y</em></span> may be due to differences in <span class="math inline"><em>x</em><sub>1</sub></span> but also due to differences in <span class="math inline"><em>x</em><sub>2</sub></span>.</p>
<div>
<blockquote>
<p><strong>Key Takeaway on Omitted Variable Bias</strong></p>
<p>When we omit an important variable from our regression: - The coefficient we estimate may be very different from the “true” effect - The direction and magnitude of bias depends on how the omitted variable relates to both <span class="math inline"><em>y</em></span> and the included <span class="math inline"><em>x</em></span> variables - Multiple regression helps us get closer to the right answer by including important covariates</p>
</blockquote>
</div>
<div class="ai-task">
<p><span class="ai-task-icon">🤖 AI PRACTICE TASK #3</span></p>
<p><strong>Prompt:</strong> “Give me a real-world example (different from the textbook) where omitted variable bias would be a serious problem. Explain what the omitted variable is, what direction the bias would go, and why.”</p>
<button class="ai-task-copy" onclick="navigator.clipboard.writeText('Give me a real-world example (different from the textbook) where omitted variable bias would be a serious problem. Explain what the omitted variable is, what direction the bias would go, and why.'); alert('Copied!')">
📋 COPY &amp; OPEN IN CLAUDE
</button>
</div>
<hr>
<h2 class="case-study anchored" data-number="1.4" id="case-study-a1-understanding-the-gender-difference-in-earnings"><span class="header-section-number">1.4</span> Case Study A1: Understanding the Gender Difference in Earnings</h2>
<div class="case-study-title">
CASE STUDY A1: UNDERSTANDING THE GENDER DIFFERENCE IN EARNINGS
</div>
<p><strong>Multiple linear regression</strong></p>
<p>We continue investigating patterns in earnings, gender, and age. The data is the same cps-earnings data that we used earlier in Chapter 9, Section 9.2: it is a representative sample of all people of age 15 to 85 in the U.S.A. in 2014.</p>
<p>Compared to Chapter 9, Section 9.2, where we focused on a single occupation, we broaden the scope of our investigation here to all employees with a graduate degree – that is, a degree higher than a 4-year college degree: these include professional, master’s, and doctoral degrees.</p>
<p>We use data on people of age 24 to 65 (to reflect the typical working age of people with these kinds of graduate degrees). We excluded the self-employed (their earnings is difficult to measure) and included those who reported 20 hours or more as their usual weekly time worked. We have 18,241 observations.</p>
<p>The dependent variable is log hourly earnings <span class="math inline">ln <em>w</em></span>. Table 10.1 shows the results from three regressions. (1) is a simple regression of <span class="math inline">ln <em>w</em></span> on a binary <span class="math inline"><em>f</em><em>e</em><em>m</em><em>a</em><em>l</em><em>e</em></span> variable. (2) is a multiple regression that includes age as well, in a linear fashion. (3) is a simple regression with age as the dependent variable and the female binary variable.</p>
<div class="code-block">
<div class="code-header">
📊 REPLICATE TABLE 10.1
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R Code to replicate Table 10.1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"cps_earnings_grad.csv"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate three models</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(lnearnings <span class="sc">~</span> female, <span class="at">data =</span> data)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(lnearnings <span class="sc">~</span> female <span class="sc">+</span> age, <span class="at">data =</span> data)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(age <span class="sc">~</span> female, <span class="at">data =</span> data)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(model1, model2, model3),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">stars =</span> <span class="fu">c</span>(<span class="st">'***'</span> <span class="ot">=</span> <span class="fl">0.01</span>, <span class="st">'**'</span> <span class="ot">=</span> <span class="fl">0.05</span>, <span class="st">'*'</span> <span class="ot">=</span> <span class="fl">0.1</span>),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">gof_omit =</span> <span class="st">"IC|Log|F|RMSE"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(<span class="st">"female"</span> <span class="ot">=</span> <span class="st">"Female"</span>, <span class="st">"age"</span> <span class="ot">=</span> <span class="st">"Age"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><a href="https://github.com/gabors-data-analysis/da_case_studies/blob/master/ch10-gender-earnings-understand/ch10-gender-earnings-multireg.ipynb" class="code-link" target="_blank">🚀 OPEN IN CODESPACE</a></p>
</div>
<p><strong>Table 10.1: Gender differences in earnings – log earnings and gender</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>(1) ln w</th>
<th>(2) ln w</th>
<th>(3) age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>female</strong></td>
<td>-0.195***</td>
<td>-0.185***</td>
<td>-1.484***</td>
</tr>
<tr class="even">
<td></td>
<td>(0.008)</td>
<td>(0.008)</td>
<td>(0.159)</td>
</tr>
<tr class="odd">
<td><strong>age</strong></td>
<td></td>
<td>0.007***</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(0.000)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Constant</strong></td>
<td>3.514***</td>
<td>3.198***</td>
<td>44.630***</td>
</tr>
<tr class="even">
<td></td>
<td>(0.006)</td>
<td>(0.018)</td>
<td>(0.116)</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Observations</strong></td>
<td>18,241</td>
<td>18,241</td>
<td>18,241</td>
</tr>
<tr class="odd">
<td><strong>R-squared</strong></td>
<td>0.028</td>
<td>0.046</td>
<td>0.005</td>
</tr>
</tbody>
</table>
<p><em>Note: All employees with a graduate degree. Robust standard error estimates in parentheses. *** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1</em><br>
<em>Source: cps-earnings dataset. 2014, U.S.A.</em></p>
<h3 data-number="1.4.1" id="interpretation-of-results" class="anchored"><span class="header-section-number">1.4.1</span> Interpretation of Results</h3>
<p>According to column (1), women in this sample earn 19.5 log points (around 21 percent) less than men, on average. Column (2) suggests that when we compare employees of the same age, women in this sample earn 18.5 log points (around 20 percent) less than men, on average. This is a slightly smaller gender difference than in column (1). While the log approximation is not perfect at these magnitudes, from now on, we will ignore the difference between log units and percent. For example, we will interpret a 0.195 coefficient as a 19.5 percent difference.</p>
<p>The estimated coefficients differ, and we know where the difference should come from: average difference in age. Let’s use the formula for the difference between the coefficient on <span class="math inline"><em>f</em><em>e</em><em>m</em><em>a</em><em>l</em><em>e</em></span> in the simple regression and in the multiple regression. Their difference is <span class="math inline">−0.195 − (−0.185) = −0.01</span>. This should be equal to the product of the coefficient of <span class="math inline"><em>f</em><em>e</em><em>m</em><em>a</em><em>l</em><em>e</em></span> in the regression of <span class="math inline"><em>a</em><em>g</em><em>e</em></span> on <span class="math inline"><em>f</em><em>e</em><em>m</em><em>a</em><em>l</em><em>e</em></span> (our column (3)) and the coefficient on <span class="math inline"><em>a</em><em>g</em><em>e</em></span> in column (2): <span class="math inline">−1.48 × 0.007 ≈ −0.01</span>. These two are indeed equal.</p>
<p>Intuitively, we can see that women of the same age have a slightly smaller earnings disadvantage in this data because they are somewhat younger, on average, and employees who are younger tend to earn less. Part of the earnings disadvantage of women is thus due to the fact that they are younger. This is a small part, though: around one percentage point of the 19.5% difference, which is a 5% share of the entire difference.</p>
<h3 data-number="1.4.2" id="why-are-women-younger-on-average" class="anchored"><span class="header-section-number">1.4.2</span> Why Are Women Younger on Average?</h3>
<p>But why are women employees younger, on average, in the data? It’s because there are fewer female employees with graduate degrees over age 45 than below. Figure 10.1 shows two density plots overlaid: the age distributions of male and female employees with graduate degrees. There are relatively few below age 30. From age 30 and up, the age distribution is close to uniform for men. But not for women: the proportion of female employees with graduate degrees drops above age 45, and again above age 55.</p>
<figure>
<img src="../../figures/Ch10_figures/ch10-figure-1-earnings-density.png" alt="Age density by gender" width="50%">
<figcaption>
<strong>Figure 10.1:</strong> Age distribution by gender. Employees with a graduate degree. Kernel density estimates. Source: cps-earnings data. U.S.A., 2014. N=18,241
</figcaption>
</figure>
<div class="code-block">
<div class="code-header">
📊 CREATE FIGURE 10.1
</div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R Code to create Figure 10.1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">fill =</span> <span class="fu">factor</span>(female, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)))) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#20C997"</span>, <span class="st">"#D63384"</span>), <span class="at">name =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age (years)"</span>, </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Age Distribution by Gender"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Employees with Graduate Degrees"</span>) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><a href="https://github.com/gabors-data-analysis/da_case_studies/blob/master/ch10-gender-earnings-understand/ch10-gender-earnings-multireg.ipynb" class="code-link" target="_blank">🚀 OPEN IN CODESPACE</a></p>
</div>
<p>In principle, this could be due to two things: either there are fewer women with graduate degrees in the 45+ generation than among the younger ones, or fewer of them are employed (i.e., employed for 20 hours or more for pay, which is the criterion to be in our subsample). Further investigation reveals that it is the former: women are less likely to have a graduate degree if they were born before 1970 (those 45+ in 2014) in the U.S.A. The proportion of women working for pay for more than 20 hours is very similar among those below age 45 and above.</p>
<div class="dashboard-box">
<div class="dashboard-box-title">
🎯 EXPLORE INTERACTIVELY
</div>
<p style="margin-bottom: 1.5rem;">
Look into conditional means by variables with our interactive dashboard. Adjust variables and watch the the graph change in real-time.
</p>
<p><a href="https://da-book-dashboards-test-ch10.streamlit.app/visualizing_relationships" class="dashboard-link" target="_blank"> OPEN DASHBOARD </a></p>
</div>
<div class="ai-task">
<p><span class="ai-task-icon">🤖 AI PRACTICE TASK #4</span></p>
<p><strong>Prompt:</strong> “Looking at Table 10.1, explain why the coefficient on ‘female’ changes from -0.195 in column (1) to -0.185 in column (2). Use the omitted variable bias formula to verify this difference mathematically.”</p>
<button class="ai-task-copy" onclick="navigator.clipboard.writeText('Looking at Table 10.1 from a regression analysis, explain why the coefficient on female changes from -0.195 in column (1) to -0.185 in column (2). Use the omitted variable bias formula to verify this difference mathematically. The coefficient on female in the age regression (column 3) is -1.484, and the coefficient on age in column 2 is 0.007.'); alert('Copied!')">
📋 COPY &amp; OPEN IN CLAUDE
</button>
</div>
<hr>
<div>
<blockquote>
<p><strong>🔗 Explore Further</strong></p>
<p><strong>Interactive Dashboard:</strong> Visualize multiple regression concepts and omitted variable bias<br>
<a href="https://dashboards.gabors-data-analysis.com/ch10">Open Dashboard</a></p>
<p><strong>Run the Analysis:</strong> Replicate all regressions and create all figures yourself<br>
<a href="https://github.com/gabors-data-analysis/da_case_studies/blob/master/ch10-gender-earnings-understand/ch10-gender-earnings-multireg.ipynb">Open in GitHub Codespace</a></p>
<p><strong>Download the Data:</strong> cps-earnings dataset<br>
<a href="https://osf.io/4vt9a/">Get Data</a></p>
</blockquote>
</div>
<hr>
<div class="page-nav">
<div class="page-nav-prev">
<pre><code>&lt;a href="index.html"&gt;← Back to Chapter 10 Index&lt;/a&gt;</code></pre>
</div>
<div class="page-nav-next">
<pre><code>&lt;a href="02-inference.html"&gt;Next: Page 2 - Statistical Inference →&lt;/a&gt;</code></pre>
</div>
</div>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>